### ISSUE TITLE
Docs build fails

### ISSUE THREAD

**Issue by elpiel** [embassy-rs/docserver#1]
latest docs build fails on the like where it open `search.js`:
https://github.com/embassy-rs/docserver/blob/d9d2791357b632f1bf2a161eeae09c7625cea6fe/src/bin/builder.rs#L280

Latest build: https://github.com/embassy-rs/embassy/actions/runs/4039037916/jobs/6943449922

**Comment by peter-lyons-kehl** [comment]
This must have got fixed - now it builds "doc (rest)" well (e.g. [merge #1295 #212](https://github.com/embassy-rs/embassy/actions/runs/4501319068/jobs/7921585963)).
